### ISSUE TITLE
Should I run transform.py?

### ISSUE THREAD

**Issue by juliowerner** [OpenTrafficCam/OTVision#230]
I am following the gui steps (view.py) and the transform step is broken.
It seems that the bug happened because ottrk format changed. 
Can I use this ottrk file? Which version of OTAnalytics do I need to read the new format?

Thanks a lot for this nice project.
Let me know if you want any help I have some time available for now.

**Comment by martinbaerwolff** [comment]
@juliowerner you are right, I fixed this in #231 which is currently under review an will be merged soon.

However, the gui itself as well as transforming tracks from pixel to world coordinates is not an official feature for now, since test coverage for this is not that high yet (we will add this later, but focus on [OTAnalytics](https://github.com/OpenTrafficCam/OTAnalytics) to derive counts from the tracks for now. 

If you want to count traffic and don´t need the tracks in world coordinates, we recommend using the cli as described on the [documentation](https://opentrafficcam.org/OTVision/gettingstarted/firstuse/)

**Comment by martinbaerwolff** [comment]
@juliowerner I close this issue as PR #231 is merged. If you have any further questions, feel free to get in touch!
