### ISSUE TITLE
Current Main Version runs into an error on windows

### ISSUE THREAD

**Issue by arminkollascheck** [OpenTrafficCam/OTVision#258]
Copyed the current main version and run the install.cmd to install all needed moduls.

After running OTVision, the window of OTVision is shotly visible and then closes.

This error occures:
![grafik](https://github.com/OpenTrafficCam/OTVision/assets/73596011/8a0e2f34-6f51-4728-ad96-d245091acac9)

Installing the dev moduls didnt fix this issue.

**Comment by arminkollascheck** [comment]
On version 1.5 it starts, on version 1.6 and 1.7 not.

**Comment by frunika** [comment]
Thanks for reporting. We'll look into it.

**Comment by joelschan** [comment]
I just recently came across Open Traffic Cam and really like your project!
Now I tried getting started with it and downloaded the latest version yesterday. It seems that I ran into the same error as described above. Since this issue has been open for a while now, I was wondering if there is a feasible workaround to still work with the OTVision and the GUI?

**Comment by arminkollascheck** [comment]
For now it only works with commends in the terminal/cmd. Look at the opentrafficcam side, there are informations how to work with it at current time.

A GUI was there some months ago, but at the current state it OTV has no GUI.
