### ISSUE TITLE
Multiprocessing and RAM-handling for tracking

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/OTVision#88]
- [ ] Start new thread on another core for each tracker (what if we want to concatenate the detections beforehand?)
- [ ] Make sure not to run out of RAM during tracking

**Comment by arminkollascheck** [comment]
For multiprocessing there are 2 ideas/issues imo:

1.  split the task of a single tracking task of a (long) video
2.  split the task of multiple tracking tasks (because you want to test results of diffrent tracker settings/trackers)

Last one is what I did in my DA. So no problem splitting it, just much RAM in usage, so you want to process the tracks in the multiprocess instead of saving them somewhere.

First one is difficult, as we already discussed you always want the data from the frame/frames befor and can't split the task easily. If there are periods of time whrere yolo detects no vehicles (longer than max gap length), you could split the tracking task there. But no idea for very vidoes of always busy intersections.

**Comment by martinbaerwolff** [comment]
As the current racker is super fast compared to detection, we do not have this on the roadmap right now.

However, if someone wants this for use scientific research, feel free to open a PR
