### ISSUE TITLE
Should IDE specific folders be removed from version control?

### ISSUE THREAD

**Issue by jibi4** [OpenTrafficCam/OTVision#91]
Should IDE specific folders be removed from version control and be added to the ` .gitignore` file? As everyone has there own individual IDE setup, I could see changes happening, for example in the `.vscode` folder, that could not apply to everyone.

**Comment by martinbaerwolff** [comment]
Hey @jibi4, questioning this totally makes sense. We decided to track vs code settings to synchronize linting and autoformatting among all developers in order to raise the chance that all formatting tests run by github actions will pass. I also think we should keep IDE specific settings to a minimum. What I see as a problem is the interpreter - whenever I change it to an interpreter inside a venv, it´s path is written to settings.json, which I do not necessarily want. But I not yet figured out a solution for that...

**Comment by frunika** [comment]
I'm with you. We should keep it at a minimum.

The venv path can be relative:

`"python.pythonPath": "venv\\Scripts\\python.exe"`

This should work for everyone using windows... maybe that's okay for the moment?


Alternatively we can add an "settings_template.json"?

**Comment by martinbaerwolff** [comment]
I am fine with this relative path (That is what is already checked in to Git). But this means we all have to use a venv. But maybe that is also fine and prevents package confusion! 

I would keep tracking the settings.json with minimum settings for the moment. 

@jibi4: If this causes problems for you, let me know!
